server:
  port: 1231

spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/studentrecord'
    username: springstudent
    password: springstudent
  main:
    banner-mode: off

logging:
  level:
    root: trace
